import { useEffect, useMemo, useState } from 'react';
import { Gamepad2, Trophy, Users, Sparkles, ArrowLeft, RotateCcw, LogOut, UserRound, Zap, Brain, Camera, Puzzle, ChevronLeft, Check, X } from 'lucide-react';
import './index.css';

type Screen='home'|'login'|'teams'|'categories'|'game'|'results';
type Team={name:string;score:number};
type Question={id:number;category:string;points:number;q:string;answers:string[];correct:number};

const games=[
{id:'teams',icon:Users,title:'قدّها فرق',desc:'فريقين، فئات، أسئلة ونقاط.',badge:'الأكثر حماسًا'},
{id:'who',icon:Brain,title:'من أنا؟',desc:'خمن الشخصية من التلميحات.'},
{id:'photo',icon:Camera,title:'تحدي الصورة',desc:'اعرف المكان أو الشخصية بسرعة.'},
{id:'fast',icon:Zap,title:'مين أسرع؟',desc:'أسئلة خاطفة تحسم الجولة.'},
{id:'words',icon:Sparkles,title:'بنك الكلمات',desc:'كلمات وحروف وتحديات سريعة.'},
{id:'character',icon:UserRound,title:'خمن الشخصية',desc:'تلميحات تدريجية ونقاط أعلى.'},
{id:'riddles',icon:Puzzle,title:'فوازير',desc:'ألغاز ممتعة بدرجات مختلفة.'},
{id:'family',icon:Trophy,title:'تحدي العائلة',desc:'إجابات شائعة ومنافسة جماعية.'}
];
const categories=[['السعودية','🇸🇦'],['رياضة','⚽'],['أفلام ومسلسلات','🎬'],['حول العالم','🌍'],['علوم','🧪'],['موسيقى','🎵'],['ألعاب','🎮'],['أكل','🍔'],['معلومات عامة','📚']].map(([name,icon])=>({name,icon}));
const raw:[string,string,string[],number][]=[
['السعودية','ما عاصمة المملكة العربية السعودية؟',['جدة','الرياض','الدمام','أبها'],1],['السعودية','أي مدينة تُعرف بعروس البحر الأحمر؟',['الرياض','جدة','الطائف','الخبر'],1],['السعودية','في أي منطقة تقع العلا؟',['المدينة المنورة','القصيم','عسير','نجران'],0],['السعودية','ما الواحة الشهيرة في شرق المملكة؟',['الأحساء','خيبر','العلا','تيماء'],0],['السعودية','أي موقع أثري في العلا مُدرج ضمن التراث العالمي؟',['رجال ألمع','مدائن صالح','المصمك','تاروت'],1],
['رياضة','كم لاعبًا يبدأ به كل فريق مباراة كرة القدم؟',['9','10','11','12'],2],['رياضة','كم شوطًا في مباراة كرة القدم العادية؟',['1','2','3','4'],1],['رياضة','في أي رياضة تستخدم الكرة البرتقالية والسلة؟',['الطائرة','السلة','اليد','التنس'],1],['رياضة','كم حلقة في شعار الألعاب الأولمبية؟',['4','5','6','7'],1],['رياضة','ما المسافة التقريبية للماراثون؟',['21 كم','30 كم','42 كم','50 كم'],2],
['أفلام ومسلسلات','من يقود تنفيذ الفيلم فنيًا؟',['المخرج','المحاسب','الموزع','الناقد'],0],['أفلام ومسلسلات','ماذا يسمى النص المكتوب للمشاهد والحوارات؟',['السيناريو','الألبوم','الملصق','المشهد'],0],['أفلام ومسلسلات','ما الاسم الشائع للحلقة التجريبية الأولى؟',['Pilot','Finale','Trailer','Cut'],0],['أفلام ومسلسلات','ماذا تسمى اللقطة بعد نهاية بعض الأفلام؟',['Cold open','Post-credit scene','Flashback','Montage'],1],['أفلام ومسلسلات','ماذا يسمى الإعلان القصير للفيلم؟',['Trailer','Score','Pilot','Frame'],0],
['حول العالم','ما أكبر قارة مساحة؟',['أفريقيا','آسيا','أوروبا','أستراليا'],1],['حول العالم','ما عاصمة فرنسا؟',['مدريد','روما','باريس','برلين'],2],['حول العالم','في أي قارة تقع البرازيل؟',['آسيا','أفريقيا','أمريكا الجنوبية','أوروبا'],2],['حول العالم','ما المحيط الأكبر؟',['الأطلسي','الهندي','الهادئ','المتجمد'],2],['حول العالم','أي دولة تشتهر بمدينة كيوتو؟',['الصين','اليابان','كوريا','تايلاند'],1],
['علوم','ما الكوكب الذي نعيش عليه؟',['المريخ','الأرض','الزهرة','المشتري'],1],['علوم','ما الغاز الذي يحتاجه الإنسان للتنفس؟',['الهيدروجين','الأكسجين','النيون','الهيليوم'],1],['علوم','كم عدد كواكب المجموعة الشمسية؟',['7','8','9','10'],1],['علوم','ما العضو الذي يضخ الدم؟',['الرئة','الكبد','القلب','المعدة'],2],['علوم','ما الرمز الكيميائي للذهب؟',['Ag','Au','Fe','Gd'],1],
['موسيقى','كم وترًا في الغيتار التقليدي غالبًا؟',['4','5','6','8'],2],['موسيقى','أي آلة فيها مفاتيح سوداء وبيضاء؟',['البيانو','الكمان','العود','الطبلة'],0],['موسيقى','من يقود الفرقة الموسيقية الكبيرة؟',['المذيع','المايسترو','الكاتب','المنتج'],1],['موسيقى','ما اسم السرعة الإيقاعية؟',['Tempo','Canvas','Frame','Tone'],0],['موسيقى','ما الآلة الوترية العربية ذات الجسم الكمثري؟',['العود','الناي','القانون','الدف'],0],
['ألعاب','ما الجهاز المستخدم للتحكم في ألعاب الكونسول؟',['يد تحكم','طابعة','ماسح','راوتر'],0],['ألعاب','ما معنى NPC غالبًا؟',['شخصية غير لاعب','نقاط إضافية','خادم شبكة','مرحلة سرية'],0],['ألعاب','ما المصطلح لمواجهة عدو نهائي قوي؟',['Boss fight','Lobby','Patch','Ping'],0],['ألعاب','ما معنى Co-op؟',['لعب تعاوني','لعب فردي','حفظ تلقائي','تحديث'],0],['ألعاب','ما المصطلح لتأخر الاستجابة عبر الإنترنت؟',['Lag','Skin','Quest','HUD'],0],
['أكل','أي فاكهة تصنع منها الزبيب؟',['العنب','التفاح','البرتقال','الموز'],0],['أكل','ما المكوّن الأساسي في الحمص الشامي؟',['العدس','الحمص','الأرز','البطاطس'],1],['أكل','ما التوابل الصفراء الشائعة في الأرز؟',['الكركم','الفلفل','الكمون','الملح'],0],['أكل','أي طبق إيطالي يعتمد على عجينة وصلصة وجبن؟',['سوشي','بيتزا','تاكو','كاري'],1],['أكل','ما المادة التي تنفخ الخبز غالبًا؟',['الخميرة','السكر','الملح','الزيت'],0],
['معلومات عامة','كم يومًا في الأسبوع؟',['5','6','7','8'],2],['معلومات عامة','ما اللون الناتج من الأزرق والأصفر؟',['أخضر','برتقالي','بنفسجي','أحمر'],0],['معلومات عامة','كم دقيقة في الساعة؟',['50','60','70','100'],1],['معلومات عامة','أي لغة تُكتب من اليمين إلى اليسار؟',['العربية','الإنجليزية','الفرنسية','الإسبانية'],0],['معلومات عامة','ما أكبر حيوان معروف على الأرض؟',['الفيل','الحوت الأزرق','الزرافة','القرش'],1]
];
const questions:Question[]=raw.map((r,i)=>({id:i+1,category:r[0],points:((i%5)+1)*100,q:r[1],answers:r[2],correct:r[3]}));

export default function App(){
const [screen,setScreen]=useState<Screen>('home');
const [profile,setProfile]=useState<{name:string;email:string}|null>(()=>{try{return JSON.parse(localStorage.getItem('qadha-profile')||'null')}catch{return null}});
const [teams,setTeams]=useState<Team[]>([{name:'الصقور',score:0},{name:'الذيبان',score:0}]);
const [selectedCats,setSelectedCats]=useState<string[]>(categories.slice(0,6).map(c=>c.name));
const [usedIds,setUsedIds]=useState<number[]>([]);const [current,setCurrent]=useState<Question|null>(null);const [turn,setTurn]=useState(0);const [answered,setAnswered]=useState<number|null>(null);const [round,setRound]=useState(1);const [activeGame,setActiveGame]=useState('teams');const maxRounds=12;
useEffect(()=>{if(profile)localStorage.setItem('qadha-profile',JSON.stringify(profile))},[profile]);
const available=useMemo(()=>questions.filter(q=>selectedCats.includes(q.category)&&!usedIds.includes(q.id)),[selectedCats,usedIds]);
const pick=(pool:Question[])=>pool[Math.floor(Math.random()*pool.length)];
const start=()=>{const q=pick(questions.filter(x=>selectedCats.includes(x.category)));setTeams(t=>t.map(x=>({...x,score:0})));setUsedIds(q?[q.id]:[]);setCurrent(q||null);setRound(1);setTurn(0);setAnswered(null);setScreen('game')};
const next=()=>{if(round>=maxRounds){setScreen('results');return}const pool=available.length?available:questions.filter(q=>selectedCats.includes(q.category));const q=pick(pool);if(q){setCurrent(q);setUsedIds(v=>[...v,q.id])}setRound(r=>r+1);setTurn(t=>t?0:1);setAnswered(null)};
const answer=(i:number)=>{if(!current||answered!==null)return;setAnswered(i);if(i===current.correct)setTeams(ts=>ts.map((t,j)=>j===turn?{...t,score:t.score+current.points}:t))};
const enterGame=(id:string)=>{setActiveGame(id);setScreen(profile?'teams':'login')};
const winner=teams[0].score===teams[1].score?null:(teams[0].score>teams[1].score?teams[0]:teams[1]);
return <div className="app" dir="rtl"><header className="topbar"><button className="brand" onClick={()=>setScreen('home')}><span className="brand-mark">ق</span><span>قدّها</span></button><nav><button onClick={()=>setScreen('home')}>الرئيسية</button><button onClick={()=>enterGame('teams')}>اللعب</button></nav><div className="profile-pill">{profile?<><UserRound size={17}/><span>{profile.name}</span><button onClick={()=>{localStorage.removeItem('qadha-profile');setProfile(null);setScreen('home')}}><LogOut size={15}/></button></>:<button onClick={()=>setScreen('login')}>دخول</button>}</div></header><main>
{screen==='home'&&<><section className="hero"><div className="hero-main"><div className="eyebrow"><Sparkles size={16}/> ألعاب جماعية • تحديات • ضحك</div><h1>مين فيكم<br/><span>قدّها؟</span></h1><p>مكان واحد يجمع ألعاب القروب والتحديات السريعة. اختاروا اللعبة، كوّنوا الفرق، وابدأوا المنافسة.</p><div className="hero-actions"><button className="primary" onClick={()=>enterGame('teams')}>ابدأ اللعب <ChevronLeft size={18}/></button><a className="secondary" href="#games">استكشف الألعاب</a></div></div><div className="hero-side"><Info value="8+" label="ألعاب متنوعة"/><Info value="45" label="سؤال كبداية"/><Info value="0" label="تكرار داخل الجولة"/></div></section><section id="games" className="section"><div className="section-head"><div><small>اختاروا جوّكم</small><h2>الألعاب</h2></div><span>كل لعبة مصممة للجلسة</span></div><div className="games-grid">{games.map(g=>{const Icon=g.icon;return <button className="game-card" key={g.id} onClick={()=>enterGame(g.id)}><span className="icon-wrap"><Icon/></span>{g.badge&&<b className="badge">{g.badge}</b>}<h3>{g.title}</h3><p>{g.desc}</p><span className="play-link">ابدأ <ArrowLeft size={16}/></span></button>})}</div></section></>}
{screen==='login'&&<section className="center-screen"><div className="form-card"><span className="icon-wrap large"><UserRound/></span><h2>دخول سريع</h2><p>نحفظ اسمك ونتائجك على هذا الجهاز فقط.</p><input id="name" placeholder="اسمك"/><input id="email" placeholder="البريد الإلكتروني" type="email"/><button className="primary full" onClick={()=>{const n=(document.getElementById('name') as HTMLInputElement).value.trim();const e=(document.getElementById('email') as HTMLInputElement).value.trim();if(n){setProfile({name:n,email:e});setScreen('teams')}}}>دخول وابدأ</button><button className="text-btn" onClick={()=>setScreen('home')}>رجوع</button></div></section>}
{screen==='teams'&&<section className="flow"><Steps current={1}/><div className="flow-head"><div><small>اللعبة: {games.find(g=>g.id===activeGame)?.title}</small><h2>كوّنوا الفرق</h2></div><span>سمّوا كل فريق</span></div><div className="team-grid">{teams.map((t,i)=><div className="team-card" key={i}><span>الفريق {i+1}</span><input value={t.name} onChange={e=>setTeams(ts=>ts.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><b>{t.score} نقطة</b></div>)}</div><div className="flow-actions"><button className="secondary" onClick={()=>setScreen('home')}>رجوع</button><button className="primary" onClick={()=>setScreen('categories')}>التالي: الفئات <ChevronLeft size={18}/></button></div></section>}
{screen==='categories'&&<section className="flow"><Steps current={2}/><div className="flow-head"><div><small>اختيار المحتوى</small><h2>اختاروا 6 فئات</h2></div><span>{selectedCats.length} / 6 مختارة</span></div><div className="cat-grid">{categories.map(c=>{const s=selectedCats.includes(c.name);return <button key={c.name} className={'cat-card '+(s?'selected':'')} onClick={()=>setSelectedCats(v=>s?v.filter(x=>x!==c.name):(v.length<6?[...v,c.name]:v))}><span>{c.icon}</span><b>{c.name}</b>{s&&<Check size={18}/>}</button>})}</div><div className="flow-actions"><button className="secondary" onClick={()=>setScreen('teams')}>رجوع</button><button className="primary" disabled={selectedCats.length<2} onClick={start}>ابدأ الجولة <Gamepad2 size={18}/></button></div></section>}
{screen==='game'&&current&&<section className="game-screen"><div className="scorebar"><Score team={teams[0]} active={turn===0}/><div className="round">الجولة <b>{round}</b> / {maxRounds}</div><Score team={teams[1]} active={turn===1}/></div><div className="question-card"><div className="q-meta"><span>{current.category}</span><b>{current.points} نقطة</b></div><small>دور فريق {teams[turn].name}</small><h2>{current.q}</h2><div className="answers">{current.answers.map((a,i)=>{let cls='answer';if(answered!==null){if(i===current.correct)cls+=' correct';else if(i===answered)cls+=' wrong'}return <button className={cls} key={i} onClick={()=>answer(i)} disabled={answered!==null}><span>{['أ','ب','ج','د'][i]}</span>{a}{answered!==null&&i===current.correct&&<Check/>}{answered===i&&i!==current.correct&&<X/>}</button>})}</div>{answered!==null&&<button className="primary continue" onClick={next}>{round>=maxRounds?'النتيجة':'السؤال التالي'} <ChevronLeft size={18}/></button>}</div></section>}
{screen==='results'&&<section className="center-screen"><div className="result-card"><div className="trophy"><Trophy/></div><small>انتهت الجولة</small><h2>{winner?`${winner.name} قدّها!`:'تعادل قوي!'}</h2><p>{teams[0].name} <b>{teams[0].score}</b> — <b>{teams[1].score}</b> {teams[1].name}</p><div className="result-actions"><button className="primary" onClick={()=>{setTeams([{name:'الصقور',score:0},{name:'الذيبان',score:0}]);setUsedIds([]);setScreen('home')}}><RotateCcw size={18}/> العبوا من جديد</button><button className="secondary" onClick={()=>setScreen('home')}>الرئيسية</button></div></div></section>}
</main><footer><span>قدّها</span><p>ألعاب جلسات عربية — نسخة أولية قابلة للتوسع</p></footer></div>}
function Info({value,label}:{value:string;label:string}){return <div className="info"><b>{value}</b><span>{label}</span></div>}
function Steps({current}:{current:number}){return <div className="steps"><span className={current>=1?'on':''}>1 الفرق</span><i></i><span className={current>=2?'on':''}>2 الفئات</span><i></i><span>3 اللعب</span></div>}
function Score({team,active}:{team:Team;active:boolean}){return <div className={'score '+(active?'active':'')}><span>{team.name}</span><b>{team.score}</b></div>}
