-- Qaddha admin live overview metrics
create or replace function private.qaddha_is_admin(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(select 1 from public.qaddha_admins where user_id = p_user_id);
$$;

revoke all on function private.qaddha_is_admin(uuid) from public, anon;
grant execute on function private.qaddha_is_admin(uuid) to authenticated;

create or replace function private.qaddha_admin_overview_impl()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  result jsonb;
begin
  if uid is null or not private.qaddha_is_admin(uid) then
    raise exception 'ADMIN_REQUIRED';
  end if;

  select jsonb_build_object(
    'users', (select count(*) from auth.users where deleted_at is null),
    'profiles', (select count(*) from public.qaddha_profiles),
    'active_24h', (select count(*) from public.qaddha_profiles where last_seen >= now() - interval '24 hours'),
    'active_rooms', (select count(*) from public.qaddha_online_rooms where status in ('waiting','ready','playing') and expires_at > now()),
    'matches_total', (select coalesce(sum(played),0) / 2 from public.qaddha_game_stats),
    'online_players', (select count(distinct user_id) from public.qaddha_online_room_members),
    'top_games', coalesce((
      select jsonb_agg(row_to_json(t))
      from (
        select game_id, sum(played)::bigint as played, sum(wins)::bigint as wins, sum(draws)::bigint as draws
        from public.qaddha_game_stats
        group by game_id
        order by sum(played) desc, game_id
        limit 6
      ) t
    ), '[]'::jsonb),
    'recent_rooms', coalesce((
      select jsonb_agg(row_to_json(r))
      from (
        select rooms.id, rooms.code, rooms.game_id, rooms.mode, rooms.status,
               rooms.created_at, rooms.updated_at, rooms.expires_at,
               count(m.user_id)::int as members
        from public.qaddha_online_rooms rooms
        left join public.qaddha_online_room_members m on m.room_id = rooms.id
        group by rooms.id
        order by rooms.updated_at desc
        limit 8
      ) r
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function private.qaddha_admin_overview_impl() from public, anon;
grant execute on function private.qaddha_admin_overview_impl() to authenticated;

create or replace function public.qaddha_admin_overview()
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.qaddha_admin_overview_impl(); $$;

revoke all on function public.qaddha_admin_overview() from public, anon;
grant execute on function public.qaddha_admin_overview() to authenticated;


-- Administrative operations, player view, room termination and audit history.
create table if not exists public.qaddha_admin_audit (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.qaddha_admin_audit enable row level security;
drop policy if exists "admins read audit log" on public.qaddha_admin_audit;
create policy "admins read audit log" on public.qaddha_admin_audit
for select to authenticated using (private.qaddha_is_admin((select auth.uid())));
grant select on public.qaddha_admin_audit to authenticated;

create or replace function private.qaddha_admin_save_config_impl(p_config jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); next_row public.qaddha_remote_config%rowtype;
begin
  if uid is null or not private.qaddha_is_admin(uid) then raise exception 'ADMIN_REQUIRED'; end if;
  update public.qaddha_remote_config set
    announcement_enabled=coalesce((p_config->>'announcement_enabled')::boolean,announcement_enabled),
    announcement_text=coalesce(p_config->>'announcement_text',announcement_text),
    maintenance_mode=coalesce((p_config->>'maintenance_mode')::boolean,maintenance_mode),
    maintenance_message=coalesce(p_config->>'maintenance_message',maintenance_message),
    content_enabled=coalesce((p_config->>'content_enabled')::boolean,content_enabled),
    sessions_enabled=coalesce((p_config->>'sessions_enabled')::boolean,sessions_enabled),
    qr_enabled=coalesce((p_config->>'qr_enabled')::boolean,qr_enabled),
    difficulty=case when p_config->>'difficulty' in ('medium','medium-hard','hard') then p_config->>'difficulty' else difficulty end,
    enabled_games=case when jsonb_typeof(p_config->'enabled_games')='array' then array(select jsonb_array_elements_text(p_config->'enabled_games')) else enabled_games end,
    updated_at=now()
  where id='global' returning * into next_row;
  if not found then raise exception 'CONFIG_NOT_FOUND'; end if;
  insert into public.qaddha_admin_audit(admin_user_id,action,target_type,target_id,details)
  values(uid,'config.update','config','global',jsonb_build_object('maintenance_mode',next_row.maintenance_mode,'content_enabled',next_row.content_enabled,'sessions_enabled',next_row.sessions_enabled,'qr_enabled',next_row.qr_enabled,'difficulty',next_row.difficulty,'enabled_games_count',coalesce(array_length(next_row.enabled_games,1),0)));
  return to_jsonb(next_row);
end;
$$;

create or replace function private.qaddha_admin_players_impl(p_limit int default 50)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); result jsonb;
begin
  if uid is null or not private.qaddha_is_admin(uid) then raise exception 'ADMIN_REQUIRED'; end if;
  select coalesce(jsonb_agg(row_to_json(p)),'[]'::jsonb) into result from (
    select u.id as user_id,u.email,q.display_name,q.xp,q.games_played,q.wins,q.last_seen,q.created_at
    from public.qaddha_profiles q join auth.users u on u.id=q.user_id
    order by q.last_seen desc nulls last limit greatest(1,least(coalesce(p_limit,50),100))
  ) p;
  return result;
end;
$$;

create or replace function private.qaddha_admin_cancel_room_impl(p_room_id uuid,p_reason text default null)
returns boolean language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); room_code text;
begin
  if uid is null or not private.qaddha_is_admin(uid) then raise exception 'ADMIN_REQUIRED'; end if;
  update public.qaddha_online_rooms set status='cancelled',updated_at=now()
  where id=p_room_id and status not in ('finished','cancelled') returning code into room_code;
  if room_code is null then return false; end if;
  delete from public.qaddha_matchmaking_queue where room_id=p_room_id;
  insert into public.qaddha_admin_audit(admin_user_id,action,target_type,target_id,details)
  values(uid,'room.cancel','online_room',p_room_id::text,jsonb_build_object('code',room_code,'reason',coalesce(nullif(left(trim(p_reason),200),''),'manual_admin_cancel')));
  return true;
end;
$$;

create or replace function private.qaddha_admin_audit_impl(p_limit int default 30)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); result jsonb;
begin
  if uid is null or not private.qaddha_is_admin(uid) then raise exception 'ADMIN_REQUIRED'; end if;
  select coalesce(jsonb_agg(row_to_json(a)),'[]'::jsonb) into result from (
    select audit.id,audit.action,audit.target_type,audit.target_id,audit.details,audit.created_at,
      coalesce(p.display_name,split_part(coalesce(u.email,'admin'),'@',1),'admin') as admin_name
    from public.qaddha_admin_audit audit
    left join public.qaddha_profiles p on p.user_id=audit.admin_user_id
    left join auth.users u on u.id=audit.admin_user_id
    order by audit.created_at desc limit greatest(1,least(coalesce(p_limit,30),100))
  ) a;
  return result;
end;
$$;

revoke all on function private.qaddha_admin_save_config_impl(jsonb) from public,anon;
revoke all on function private.qaddha_admin_players_impl(int) from public,anon;
revoke all on function private.qaddha_admin_cancel_room_impl(uuid,text) from public,anon;
revoke all on function private.qaddha_admin_audit_impl(int) from public,anon;
grant execute on function private.qaddha_admin_save_config_impl(jsonb) to authenticated;
grant execute on function private.qaddha_admin_players_impl(int) to authenticated;
grant execute on function private.qaddha_admin_cancel_room_impl(uuid,text) to authenticated;
grant execute on function private.qaddha_admin_audit_impl(int) to authenticated;

create or replace function public.qaddha_admin_save_config(p_config jsonb)
returns jsonb language sql security invoker set search_path='' as $$ select private.qaddha_admin_save_config_impl(p_config); $$;
create or replace function public.qaddha_admin_players(p_limit int default 50)
returns jsonb language sql security invoker set search_path='' as $$ select private.qaddha_admin_players_impl(p_limit); $$;
create or replace function public.qaddha_admin_cancel_room(p_room_id uuid,p_reason text default null)
returns boolean language sql security invoker set search_path='' as $$ select private.qaddha_admin_cancel_room_impl(p_room_id,p_reason); $$;
create or replace function public.qaddha_admin_audit(p_limit int default 30)
returns jsonb language sql security invoker set search_path='' as $$ select private.qaddha_admin_audit_impl(p_limit); $$;

revoke all on function public.qaddha_admin_save_config(jsonb) from public,anon;
revoke all on function public.qaddha_admin_players(int) from public,anon;
revoke all on function public.qaddha_admin_cancel_room(uuid,text) from public,anon;
revoke all on function public.qaddha_admin_audit(int) from public,anon;
grant execute on function public.qaddha_admin_save_config(jsonb) to authenticated;
grant execute on function public.qaddha_admin_players(int) to authenticated;
grant execute on function public.qaddha_admin_cancel_room(uuid,text) to authenticated;
grant execute on function public.qaddha_admin_audit(int) to authenticated;
